.kaniko-build:
  stage: build
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat <<EOF > /kaniko/.docker/config.json
        {
          "auths":{
            "${CI_REGISTRY}":{
              "auth":"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')"
            },
            "https://index.docker.io/v1/":{
              "auth":"$(printf "%s:%s" "${DOCKERHUB_USERNAME}" "${DOCKERHUB_PASSWORD}" | base64 | tr -d '\n')"
            }
          }
        }
      EOF
    - cat /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${DOCKERFILE_PATH}"
      --destination "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --cache
    - echo $(date) $(date)
  image:     
    name: gcr.io/kaniko-project/executor:v1.8.0-debug
    entrypoint: [""]

test-build:
  extends: .kaniko-build
  when: manual
  variables:
    DOCKERFILE_PATH: "$CI_COMMIT_BRANCH"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
  interruptible: true

test-deploy:
  interruptible: true
  #when: manual
  needs: 
    - test-build
  image: $CI_REGISTRY/Kubernetes
  stage: deploy
  script:
    - kubectl create secret docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run=client | kubectl apply -f -
    - kubectl get pod -A
    - cat kubernetes/configmap.yaml | envsubst | kubectl apply -f -
    - cat kubernetes/deployment.yaml | envsubst | kubectl apply -f -
    - cat kubernetes/service.yaml | envsubst | kubectl apply -f -
    - cat kubernetes/ingress.yaml | envsubst | kubectl apply -f -
   
  after_script: 
    - kubectl rollout status deployment ideasoft-test -n ideasoft
  environment:
    name: test-ideasoft
    kubernetes:
      namespace: ideasoft
